### ISSUE TITLE
Can this library be used in java project?

### ISSUE THREAD

**Issue by uzaysan** [ibrahimsn98/NiceBottomBar#3]
Hi. I your library look great. But seems like its written in kotlin. But my project is in java can I use this library in my project?

**Comment by ibrahimsn98** [comment]
Yep, you can use.

**Comment by LuisFVargas** [comment]
ERROR: Failed to resolve: com.github.ibrahimsn98:NiceBottomBar:1.8.0
Show in Project Structure dialog
Affected Modules: app 
any help ? 
another question : is it possible to change the position of the line indicator ? I want it to be above not below

**Comment by brookmg** [comment]
Hey Luis, 

- First the gradle error could be cause because of connection issue or because you enabled offline mode in Android Studio setting.

- And yes you can choose the position of the indicator (above or bottom) using xml or code

**Comment by waqaruet** [comment]
No documentation for how to use in java?
