### ISSUE TITLE
BottomBar bottom margin

### ISSUE THREAD

**Issue by am3n** [ibrahimsn98/NiceBottomBar#5]
tnx for lib 👍 
when indicator is disabled, bottom margin that used for indicator must be 0

**Comment by LuisFVargas** [comment]
missing feautures
text size difference between selected and not selected
elevation as the original
line indicator color

**Comment by brookmg** [comment]
Hey Luis, can you create new issue if it's not related with the title. Would also help if you could elaborate what the issue is
